### ISSUE TITLE
代码提交的安全扫描关不了，关闭之后重新打开又选上了，如果是BUG请解决一下

### ISSUE THREAD

**Issue by YunlongChen** [murphysecurity/murphysec-jetbrains-plugin#16]
![图片](https://github.com/murphysecurity/murphysec-jetbrains-plugin/assets/31004541/9aa9bd3c-5df1-4f36-9fe6-e323934c1dd1)

**Comment by CN-You** [comment]
感谢您的反馈，关闭之后重新打开是插件BUG，我们会在最近的插件升级版本中解决掉
