### ISSUE TITLE
在goland中不能使用进行扫描go

### ISSUE THREAD

**Issue by qiangmzsx** [murphysecurity/murphysec-jetbrains-plugin#2]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/4846144/159222851-f342ee2f-0df6-47ae-8c13-fd44212c19e8.png">

**Comment by CN-You** [comment]
感谢您的反馈，方便我们通过邮件联系您了解下具体的情况吗？

**Comment by qiangmzsx** [comment]
> 感谢您的反馈，方便我们通过邮件联系您了解下具体的情况吗？

可以的，qiangmzsx@hotmail.com

**Comment by CN-You** [comment]
收到，我们通过邮件联系

**Comment by CN-You** [comment]
该问题主要是因为插件运行环境中Go命令执行异常导致的

如果Go的项目检测爆出错误，可以在项目根目录下执行`go mod tidy`，如果执行失败请首先检查当前环境Go是否配置正常。

我们后续会优化报错的内容
