### ISSUE TITLE
IDEA无法识别项目

### ISSUE THREAD

**Issue by zhaobingss** [murphysecurity/murphysec-jetbrains-plugin#3]
在idea中，如果当前project有多个module和其他的非java的module会导致插件无法识别项目

**Comment by CN-You** [comment]
感谢反馈，之前我们是在项目根目录下寻找包管理文件（例如pom.xml），当项目有多个module的情况时可能会导致检测失败。

这个问题已经解决，我们将在明天上午发布新版（V2.0.5），到时候您可以直接在IDE中升级插件。

**Comment by CN-You** [comment]
v2.0.5插件已发布 [https://plugins.jetbrains.com/plugin/18274-murphysec-code-scan](https://plugins.jetbrains.com/plugin/18274-murphysec-code-scan)

可以直接在IDE中升级
