### ISSUE TITLE
增加侧边下拉框

### ISSUE THREAD

**Issue by cwkiller** [murphysecurity/murphysec-jetbrains-plugin#4]
建议红框处增加和右边箭头处同样的下拉框
![image](https://user-images.githubusercontent.com/19302055/162664494-a9bc6637-ee2b-4f35-81aa-cbae3cb409b3.png)

**Comment by xuxiaowei-com-cn** [comment]
https://github.com/murphysecurity/murphysec/issues/8

**Comment by xuxiaowei-com-cn** [comment]
在v2.0.7中已更新
![idea64_XbXubZ3pMg](https://user-images.githubusercontent.com/46893436/163412805-099fb368-4a23-4363-b6a1-3b78166a2def.png)
