### ISSUE TITLE
建议增加排除项

### ISSUE THREAD

**Issue by icesugar** [murphysecurity/murphysec-jetbrains-plugin#5]
![](https://files.catbox.moe/j6kc64.png)
某些问题是不需要解决或解决不了的，允许排除，否则每次检测结果都要去单独看一下。
还有就是检车结果，点击左侧树右侧显示的内容最好能选中复制，现在只能看着。

**Comment by CN-You** [comment]
收到您的反馈，最近我们会发布IDE插件新版本，其中会增加白名单的功能来对某些组件进行忽略，同时也支持右侧内容的复制。插件新版本上线后我会在这里提醒您

**Comment by Claire887** [comment]
@icesugar 哈喽 插件已经上线了新版本3.0，增加了组件忽略、漏洞信息复制、提升了修复率等等能力，欢迎体验！

**Comment by icesugar** [comment]
试了下，按照依赖组件来忽略。
能否配置不扫描整个maven项目的某个模块，例如整个项目中的有个demo模块，放了和其他产品的集成，而其他产品本身依赖的版本低，导致会被扫描出来。但是我自己的非demo的其他模块需要扫描。

还有就是快速修复点了没用。
![](https://files.catbox.moe/w1xgn0.png)

**Comment by CN-You** [comment]
非常感谢您的反馈，支持忽略某个模块的需求我们收到了，快速修复点击无效的问题我们联系下您看下具体情况

**Comment by CN-You** [comment]
@icesugar 方便提供下您的邮箱吗，或者您直接扫描二维码添加我们的运营同学，谢谢

![image](https://user-images.githubusercontent.com/99465056/178188220-d204d762-2867-4916-bdbc-b741bd7b8c3c.png)

**Comment by icesugar** [comment]
就这个项目 https://gitee.com/zlt2000/microservices-platform.git
估计是因为spring-cloud-starter-gateway的依赖版本是在spring-cloud-dependencies里，而在扫描到的pom里没有指定版本所以没改到version。

还有就是现在的右侧选中按钮不好用。例如我上面发的内容，就需要先点复制按钮，然后粘贴到记事本，再选中复制，粘贴到这个输入框。
