### ISSUE TITLE
分析结果很离谱

### ISSUE THREAD

**Issue by junmowen** [murphysecurity/murphysec-jetbrains-plugin#8]
我都已经移除了jar包，检测还是有个这个jar存在漏洞需要修复

**Comment by junmowen** [comment]
![image](https://user-images.githubusercontent.com/31611137/179163065-a09bfb44-5897-4715-8040-b440abf5dd11.png)
![image](https://user-images.githubusercontent.com/31611137/179163135-272b6e46-795b-467e-b77b-d26719d50b8f.png)

**Comment by junmowen** [comment]
![image](https://user-images.githubusercontent.com/31611137/179163457-2f689aa9-1e51-4cc4-90a7-39cdedeabc99.png)
![image](https://user-images.githubusercontent.com/31611137/179163518-2606c910-fbc6-4212-8fe3-4dea95f81553.png)
这个jar 都木有了

**Comment by Claire887** [comment]
@junmowen 收到您的反馈，咱们wx也进行了交流，定位到了maven的问题，这个我们问题我们也会思考在产品上能够提示或者解决。非常感谢您的建议，之后多交流多交流🤝🤝
